### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Venomstone99** [Blatzar/shiro-app#82] opened 2021-07-17 04:03 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour
I started downloading haikyuu episodes
It downloads 3 times just to download one episode 😐
My all data wasted

**Screenshots**

**Please complete the following information:**
 - Android version :- 12
 - App version:- 2.5.3
 - Phone model:- redmi note 7s

**Additional context**

**Comment by Blatzar** [comment] 2021-07-17 10:53
I'm sorry about wasting your data and I'll try to make a setting to prevent downloading on data to alleviate unintended downloads on data.

I cannot reproduce the bug howeve. Did it happen after you reopened the app? Did it download it in the background without notification? Does it still happen every time you open the APP? Any more info will help.

**Comment by Blatzar** [comment] 2021-07-25 12:35
pretty sure it's fixed in the beta, reopen the issue if that's not the case

**Closed by Blatzar** 2021-07-25 12:35 UTC
