### ISSUE TITLE
Please add a feature Recommendation/similar 

### ISSUE THREAD

**Issue by Bungeexgum** [Blatzar/shiro-app#128] opened 2021-09-05 07:50 UTC
**Describe the bug**

**To Reproduce**

**Screenshots**

**Please complete the following information:**
 - Android version
 - App version
 - Phone model

**Additional context**
Add any other context about the

**Comment by Blatzar** [comment] 2021-09-05 16:50
Duplicate of https://github.com/Blatzar/shiro-app/issues/44

**Closed by Blatzar** 2021-09-05 16:50 UTC
